[build]
  publish = "."
  functions = "netlify/functions"

[build.processing]
  skip_processing = true

[[headers]]
  for = "assets/icons/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "data/*"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
